databases:
  - name: pgpostgres_free
    ipAllowList: []
    plan: free

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pgpostgres_free
          property: connectionString
      - key: RAILS_MASTER_KEY_BB
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction